# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kOylWRSRlP2kEdQEXQeWw5y7LtMY605
"""

!pip install -q kagglehub langchain langchain-community langchain-google-genai faiss-cpu sentence-transformers

import kagglehub
import os
import pandas as pd

# prefer local CSV in repo to avoid Kaggle download
# you can also set CHRONOLENS_DATA_CSV environment variable to point at any CSV
env_csv = os.environ.get("CHRONOLENS_DATA_CSV")
if env_csv:
    local_csv = env_csv
else:
    local_csv = os.path.join(os.path.dirname(__file__), "updated_data.csv")

if os.path.exists(local_csv):
    print("Loading dataset from CSV", local_csv)
    df = pd.read_csv(local_csv)
else:
    path = kagglehub.dataset_download("jainamgada45/indian-government-schemes")
    print("Dataset path:", path)
    # list files
    print(os.listdir(path))
    df = pd.read_csv(os.path.join(path, os.listdir(path)[0]))

# drop stray unnamed columns
if df is not None:
    df = df.drop(columns=[col for col in df.columns if "Unnamed" in col], errors="ignore")
    print(df.head())

df = df.drop(columns=[col for col in df.columns if "Unnamed" in col], errors="ignore")
df.columns

from langchain_core.documents import Document


documents = []

for _, row in df.iterrows():
    content = f"""
    Scheme Name: {row['scheme_name']}
    Category: {row['schemeCategory']}
    Level: {row['level']}
    Tags: {row['tags']}

    Details:
    {row['details']}

    Benefits:
    {row['benefits']}

    Eligibility:
    {row['eligibility']}

    Application Process:
    {row['application']}

    Required Documents:
    {row['documents']}
    """

    documents.append(
        Document(
            page_content=content.strip(),
            metadata={
                "scheme_name": row["scheme_name"],
                "category": row["schemeCategory"],
                "level": row["level"],
                "tags": row["tags"],
                "slug": row["slug"]
            }
        )
    )

len(documents)

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=120
)

docs = text_splitter.split_documents(documents)

print("Total chunks:", len(docs))

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

texts = [d.page_content for d in docs]
metadatas = [d.metadata for d in docs]

vectorstore = FAISS.from_texts(
    texts=texts,
    embedding=embeddings,
    metadatas=metadatas
)

# SAVE so you don’t redo this again like a clown
vectorstore.save_local("govt_schemes_faiss")

print("FAISS index built & saved")

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 5}
)

!pip install -q langchain

!pip install -q transformers accelerate torch

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

model_id = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

llm_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=300,
    temperature=0.1,
    do_sample=False
)

from langchain_community.llms import HuggingFacePipeline

llm = HuggingFacePipeline(pipeline=llm_pipeline)

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

prompt = ChatPromptTemplate.from_template("""
You are an assistant answering questions about Indian government schemes.
Use ONLY the provided context.

Context:
{context}

Question:
{question}

Answer clearly and factually.
""")

rag_chain = (
    {
        "context": retriever,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
    | StrOutputParser()
)

response = rag_chain.invoke(
    "Which schemes are available for women entrepreneurs and what benefits do they provide?"
)

print(response)